import slider from "./slider.js";
slider();
import story from "./story.js";
story();
import ielts from "./ielts.js";
ielts();
import discount from "./discount.js";
discount();
import phone from "./phone.js";
phone();
import favphone from "./favphone.js";
favphone();
import speaker from "./speaker.js";
speaker();
import bestphone from "./bestphone.js";
bestphone();
import laptop from "./laptop.js";
laptop();
import favsell from "./favsell.js";
favsell();
import bestsell from "./bestsell.js";
bestsell();